# Regression

In [2]:
import pandas as pd
df= pd.read_csv("ice_cream_sales.csv")
df

Temperature  Ice Cream Profits
0             39              13.17
1             40              11.88
2             41              18.82
3             42              18.65
4             43              17.02
..           ...                ...
360           99              85.13
361           99              87.08
362           99              89.29
363          101              81.91
364          101              85.02

[365 rows x 2 columns]

In [3]:
df.dtypes

Temperature            int64
Ice Cream Profits    float64
dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Temperature        365 non-null    int64  
 1   Ice Cream Profits  365 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 5.8 KB


In [5]:
!pip install scikit-learn

In [6]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
X = df[["Temperature"]]
y = df[["Ice Cream Profits"]]
model.fit(X,y)
test=model.predict([[99]])

c:\Users\admin\Desktop\PRINCE\OJT-AI\ojt\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [8]:
test

array([[84.31071797]])

In [15]:
import numpy as np
np.random.seed(19)
temps=np.random.randint(25,100,8)
temps=np.sort(temps, kind="mergesort")
temps

array([44, 47, 56, 65, 77, 81, 91, 99], dtype=int32)

In [16]:
import pandas as pd
sales_pred = pd.DataFrame({"Temperature":temps})
sales_pred

Temperature
0           44
1           47
2           56
3           65
4           77
5           81
6           91
7           99

In [17]:
results= model.predict(sales_pred[['Temperature']])
results

array([[18.75022687],
       [22.32625366],
       [33.05433402],
       [43.78241438],
       [58.08652153],
       [62.85455724],
       [74.77464653],
       [84.31071797]])

In [18]:
sales_pred["Predicted_Profits"]=results
sales_pred

Temperature  Predicted_Profits
0           44          18.750227
1           47          22.326254
2           56          33.054334
3           65          43.782414
4           77          58.086522
5           81          62.854557
6           91          74.774647
7           99          84.310718

# Classification

In [33]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

mock=pd.read_csv("Mock_Student_Scores.csv")
mock

model= LogisticRegression()
X=mock[['Score']]
y=mock[['Verdict']]
model.fit(X,y.values.ravel())

test_input = pd.DataFrame([[90.928470]], columns=['Score'])
test=model.predict(test_input)
test



array(['Superb'], dtype=object)

In [27]:
import numpy as np
np.random.seed(19)
sc=np.random.randint(25,100,8)
sc=np.sort(sc, kind="mergesort")

sc_pred = pd.DataFrame({"Score":sc})

results = model.predict(sc_pred[['Score']])
sc_pred["Predicted"]=results
sc_pred


Score Predicted
0     44  Mediocre
1     47  Mediocre
2     56   Average
3     65   Average
4     77      Good
5     81      Good
6     91    Superb
7     99    Superb